- hosts: aruba_ap
  collections:
    - arubanetworks.aruba_central
  tasks:
    - name: Show
      arubanetworks.aruba_central.aruba_cli_command:
        command: show running-config
      register: output

    - name: Display the running-config
      ansible.builtin.debug:
        var: output.stdout