- hosts: aruba_ap
  gather_facts: no
  tasks:
    - name: Show running-config on Aruba AP
      ansible.netcommon.cli_command:
        command: show running-config
      register: output

    - name: Display the running-config
      ansible.builtin.debug:
        var: output.stdout